---
- name: check if homebrew is already installed
  tags: brew
  stat:
    path: /usr/local/bin/brew
  register: hb

- name: install homebrew if not exists
  tags: brew
  script: install-homebrew.sh
  when: not hb.stat.exists

- name: update homebrew
  tags: brew
  homebrew: 
    update_homebrew: yes

- name: install homebrew packages (this may take some time) 
  tags: brew
  homebrew:
    name: "{{ brew_pkgs }}"
    state: present

- name: install homebrew casks (this may take some time)
  tags: brew
  homebrew_cask: 
    name: "{{ brew_casks }}"
    state: present


- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: installation|success
  register: cloning
  sudo: no

- name: Creating new ~/.zshrc
  copy:
    src=~/.oh-my-zsh/templates/zshrc.zsh-template
    dest=~/.zshrc
  when: cloning|success
  sudo: no